apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: order-service:latest
        ports:
        - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: ClusterIP
  ports:
  - port: 8060
    targetPort: 8060
  selector:
    app: orderservice
